---

dependencies: []

galaxy_info:

  author:              Elao
  company:             Elao
  description: >
    A phantomjs role to install phantomjs.
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - jessie
  categories:
    - development
    - web
